apiVersion: v1
kind: Service
metadata:
  name: "c001"
  namespace: c001
  labels:
    app: "ux-kcd-argentina"
    team: "C001"
    employee-id: "10001"
    framework: "Quarkus"
    managed-by: "platform-engineering"
spec:
  type: ClusterIP
  selector:
    app: "ux-kcd-argentina"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
