apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: C008
  name: "c008"
  labels:
    app: "josua"
    team: "C008"
    employee-id: "10008"
    framework: "Quarkus"
    managed-by: "platform-engineering"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "josua"
  template:
    metadata:
      labels:
        app: "josua"
        team: "C008"
        employee-id: "10008"
        framework: "Quarkus"
        managed-by: "platform-engineering"
    spec:
      containers:
        - name: josua
          image: guopingjia/mario:cfe-demo
          ports:
            - containerPort: 80
              protocol: TCP
