apiVersion: v1
kind: Service
metadata:
  name: "c008"
  namespace: C008
  labels:
    app: "josua"
    team: "C008"
    employee-id: "10008"
    framework: "Quarkus"
    managed-by: "platform-engineering"
spec:
  type: ClusterIP
  selector:
    app: "josua"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
