apiVersion: v1
kind: Service
metadata:
  name: post-apis-service
  namespace: post-apis
  labels:
    app: post-apis
    team: C004
    employee-id: 10004
    framework: Quarkus
    managed-by: platform-engineering
spec:
  type: ClusterIP
  selector:
    app: post-apis
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
