apiVersion: v1
kind: Service
metadata:
  name: ux-kcd-argentina
  namespace: C005
  labels:
    app: "ux-kcd-argentina"
    team: "C005"
    employee-id: "10005"
    framework: "Quarkus"
    managed-by: "platform-engineering"
spec:
  type: ClusterIP
  selector:
    app: "ux-kcd-argentina"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
